-- PostgreSQL Database Schema for DeadlineOS
-- Compliance calendar and filing tracker for Indian SMBs
-- Compatible with Supabase and standard PostgreSQL installations

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. WORKSPACES
CREATE TABLE workspaces (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    owner_user_id TEXT NOT NULL, -- Hooked up to Clerk User ID or OAuth ID
    plan_tier TEXT NOT NULL DEFAULT 'starter' CHECK (plan_tier IN ('starter', 'growth', 'business')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for workspace lookups by owner
CREATE INDEX idx_workspaces_owner ON workspaces(owner_user_id);

-- 2. ENTITIES (Businesses registered within a workspace)
CREATE TABLE entities (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    gstin TEXT UNIQUE,
    pan TEXT,
    tan TEXT,
    business_type TEXT NOT NULL CHECK (business_type IN ('Pvt Ltd', 'LLP', 'Sole Prop', 'Partnership', 'OPC')),
    state_code TEXT NOT NULL, -- e.g., 'MH', 'KA', 'DL', etc.
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_entities_workspace ON entities(workspace_id);
CREATE INDEX idx_entities_gstin ON entities(gstin);

-- 3. OBLIGATION TYPES (Master data of tax and corporate filings)
CREATE TABLE obligation_types (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('GST', 'TDS', 'Income Tax', 'ROC', 'PF & ESIC', 'Corporate')),
    frequency TEXT NOT NULL CHECK (frequency IN ('monthly', 'quarterly', 'annual')),
    governing_body TEXT NOT NULL, -- e.g. 'CBIC', 'Income Tax Dept', 'MCA'
    applicable_entity_types TEXT[] NOT NULL, -- e.g. {'Pvt Ltd', 'LLP'}
    typical_due_offset_days INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Seed values index
CREATE INDEX idx_obligation_types_category ON obligation_types(category);

-- 4. ENTITY OBLIGATIONS (Specific rules configured/assigned to an Entity)
CREATE TABLE entity_obligations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    entity_id UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    obligation_type_id UUID NOT NULL REFERENCES obligation_types(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    custom_due_offset INTEGER DEFAULT 0, -- offset adjustments if needed
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(entity_id, obligation_type_id)
);

CREATE INDEX idx_entity_obligations_entity ON entity_obligations(entity_id);

-- 5. DEADLINES (Calculated filing dates generated by the engine)
CREATE TABLE deadlines (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    entity_obligation_id UUID NOT NULL REFERENCES entity_obligations(id) ON DELETE CASCADE,
    due_date DATE NOT NULL,
    period_label TEXT NOT NULL, -- e.g., 'April 2026', 'Q1 FY 2026-27'
    status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'due_soon', 'filed', 'overdue')),
    readiness_score INTEGER NOT NULL DEFAULT 40 CHECK (readiness_score BETWEEN 0 AND 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_deadlines_due_date ON deadlines(due_date);
CREATE INDEX idx_deadlines_status ON deadlines(status);
CREATE INDEX idx_deadlines_obligation ON deadlines(entity_obligation_id);

-- 6. FILING RECORDS (Historic verification log when a filing is marked complete)
CREATE TABLE filing_records (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    deadline_id UUID NOT NULL UNIQUE REFERENCES deadlines(id) ON DELETE CASCADE,
    filed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    filed_by TEXT NOT NULL, -- name/email of agent who filed
    ack_number TEXT NOT NULL, -- Government ARN/Ack number
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. DOCUMENTS (Filing attachments, PDFs, Chalan receipts)
CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    entity_id UUID NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    deadline_id UUID REFERENCES deadlines(id) ON DELETE SET NULL,
    filename TEXT NOT NULL,
    s3_key TEXT NOT NULL, -- object storage reference URL or key
    document_type TEXT NOT NULL, -- e.g. 'GSTR-3B Ack', 'TDS Challan'
    uploaded_by TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_documents_entity ON documents(entity_id);
CREATE INDEX idx_documents_deadline ON documents(deadline_id);

-- 8. NOTIFICATIONS (Dispatch alerts logs)
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    deadline_id UUID REFERENCES deadlines(id) ON DELETE SET NULL,
    channel TEXT NOT NULL CHECK (channel IN ('email', 'whatsapp', 'in_app')),
    status TEXT NOT NULL DEFAULT 'sent' CHECK (status IN ('pending', 'sent', 'failed')),
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    message_content TEXT NOT NULL
);

CREATE INDEX idx_notifications_workspace ON notifications(workspace_id);

-- 9. AUDIT LOGS (Compliance-grade record keeping)
CREATE TABLE audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL, -- e.g., 'CREATE_ENTITY', 'MARK_FILED'
    table_name TEXT NOT NULL,
    record_id UUID NOT NULL,
    payload JSONB, -- store snap of changes
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. ADVISOR RELATIONSHIPS (CA Partnership mapping)
CREATE TABLE advisor_relationships (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    advisor_user_id TEXT NOT NULL, -- CA User Unique ID
    client_workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    access_level TEXT NOT NULL DEFAULT 'read' CHECK (access_level IN ('read', 'annotate')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'rejected')),
    invited_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at TIMESTAMPTZ,
    UNIQUE(advisor_user_id, client_workspace_id)
);

CREATE INDEX idx_advisor_relationships_advisor ON advisor_relationships(advisor_user_id);
CREATE INDEX idx_advisor_relationships_workspace ON advisor_relationships(client_workspace_id);


-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

-- Enable security on multi-tenant tables
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE entities ENABLE ROW LEVEL SECURITY;
ALTER TABLE entity_obligations ENABLE ROW LEVEL SECURITY;
ALTER TABLE deadlines ENABLE ROW LEVEL SECURITY;
ALTER TABLE filing_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisor_relationships ENABLE ROW LEVEL SECURITY;

-- JWT claims helper: Extracts Clerk auth ID from session JWT
CREATE OR REPLACE FUNCTION get_current_user_id()
RETURNS TEXT AS $$
    SELECT NULLIF(current_setting('request.jwt.claims', true)::json->>'sub', '');
$$ LANGUAGE sql STABLE;

-- RLS POLICY: Workspaces
CREATE POLICY workspace_select ON workspaces
    FOR SELECT USING (
        owner_user_id = get_current_user_id()
        OR EXISTS (
            SELECT 1 FROM advisor_relationships 
            WHERE advisor_relationships.client_workspace_id = id 
            AND advisor_relationships.advisor_user_id = get_current_user_id()
            AND advisor_relationships.status = 'active'
        )
    );

CREATE POLICY workspace_modify ON workspaces
    FOR ALL USING (owner_user_id = get_current_user_id());

-- RLS POLICY: Entities
CREATE POLICY entities_select ON entities
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM workspaces 
            WHERE workspaces.id = workspace_id 
            AND (
                workspaces.owner_user_id = get_current_user_id()
                OR EXISTS (
                    SELECT 1 FROM advisor_relationships 
                    WHERE advisor_relationships.client_workspace_id = workspaces.id 
                    AND advisor_relationships.advisor_user_id = get_current_user_id()
                    AND advisor_relationships.status = 'active'
                )
            )
        )
    );

CREATE POLICY entities_modify ON entities
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM workspaces 
            WHERE workspaces.id = workspace_id 
            AND workspaces.owner_user_id = get_current_user_id()
        )
    );

-- RLS POLICY: Deadlines
CREATE POLICY deadlines_select ON deadlines
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM entity_obligations eo
            JOIN entities e ON eo.entity_id = e.id
            JOIN workspaces w ON e.workspace_id = w.id
            WHERE eo.id = entity_obligation_id
            AND (
                w.owner_user_id = get_current_user_id()
                OR EXISTS (
                    SELECT 1 FROM advisor_relationships 
                    WHERE advisor_relationships.client_workspace_id = w.id 
                    AND advisor_relationships.advisor_user_id = get_current_user_id()
                    AND advisor_relationships.status = 'active'
                )
            )
        )
    );

CREATE POLICY deadlines_modify ON deadlines
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM entity_obligations eo
            JOIN entities e ON eo.entity_id = e.id
            JOIN workspaces w ON e.workspace_id = w.id
            WHERE eo.id = entity_obligation_id
            AND w.owner_user_id = get_current_user_id()
        )
    );


-- ==========================================
-- MASTER SEED DATA
-- ==========================================
INSERT INTO obligation_types (name, category, frequency, governing_body, applicable_entity_types, typical_due_offset_days) VALUES
('GSTR-1 (Sales Return)', 'GST', 'monthly', 'CBIC', '{"Pvt Ltd", "LLP", "Sole Prop", "OPC", "Partnership"}', 11),
('GSTR-3B (Summary Return)', 'GST', 'monthly', 'CBIC', '{"Pvt Ltd", "LLP", "Sole Prop", "OPC", "Partnership"}', 20),
('TDS Challan Payment (Section 192/194)', 'TDS', 'monthly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC"}', 7),
('TDS Quarterly Return (Form 24Q/26Q) Q1', 'TDS', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC"}', 31),
('TDS Quarterly Return (Form 24Q/26Q) Q2', 'TDS', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC"}', 31),
('TDS Quarterly Return (Form 24Q/26Q) Q3', 'TDS', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC"}', 31),
('TDS Quarterly Return (Form 24Q/26Q) Q4', 'TDS', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC"}', 31),
('Advance Tax installment 1 (15%)', 'Income Tax', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC", "Partnership"}', 15),
('Advance Tax Installment 2 (45%)', 'Income Tax', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC", "Partnership"}', 15),
('Advance Tax Installment 3 (75%)', 'Income Tax', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC", "Partnership"}', 15),
('Advance Tax Installment 4 (100%)', 'Income Tax', 'quarterly', 'Income Tax Dept', '{"Pvt Ltd", "LLP", "OPC", "Partnership"}', 15),
('ROC DIR-3 KYC Director KYC', 'ROC', 'annual', 'MCA', '{"Pvt Ltd", "OPC"}', 30),
('ROC MGT-7 Annual Return', 'ROC', 'annual', 'MCA', '{"Pvt Ltd", "OPC"}', 60),
('ROC AOC-4 Financial Statements', 'ROC', 'annual', 'MCA', '{"Pvt Ltd", "OPC"}', 30),
('Provident Fund (PF) Monthly Return', 'PF & ESIC', 'monthly', 'EPFO', '{"Pvt Ltd", "LLP", "Partnership"}', 15),
('ESIC Monthly Contribution Return', 'PF & ESIC', 'monthly', 'ESIC', '{"Pvt Ltd", "LLP", "Partnership"}', 15);
